export const Posts = [
  {
    title: "Інтернет-магазин Urban Outfitters у UK: огляд",
    image: "1.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Overstock. Брендові товари за доступними цінами",
    image: "2.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Skechers з Amazon. Зручна взуття для всієї родини",
    image: "3.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "16 найкращих подарунків з Амазону у 2023 році",
    image: "4.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Target – сімейний супермаркет із цінами від 300 рублів!",
    image: "5.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Англійський магазин RIPNDIP. Купуємо самовираження",
    image: "6.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Nautica. Елітні товари з Англії за низькими цінами",
    image: "7.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Forever 21 - купуємо джинси за 1500 грн",
    image: "8.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Як купити кросівки Balenciaga на 30 000 грн дешевше?",
    image: "9.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Інтернет-магазин Urban Outfitters у UK: огляд",
    image: "1.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Overstock. Брендові товари за доступними цінами",
    image: "2.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Skechers з Amazon. Зручна взуття для всієї родини",
    image: "3.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "16 найкращих подарунків з Амазону у 2023 році",
    image: "4.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Target – сімейний супермаркет із цінами від 300 рублів!",
    image: "5.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Англійський магазин RIPNDIP. Купуємо самовираження",
    image: "6.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Nautica. Елітні товари з Англії за низькими цінами",
    image: "7.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Forever 21 - купуємо джинси за 1500 грн",
    image: "8.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
  {
    title: "Як купити кросівки Balenciaga на 30 000 грн дешевше?",
    image: "9.png",
    readtime: "12",
    dateOfPublication: "20.07.2023",
  },
];
