export const Products = [
  {
    name: "222 Columbia Barlow Pass 550 Turbodown Jacket",
    image: "ColumbiaBarlow.png",
    priceUk: 80.62,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },
  {
    name: "Columbia Barlow Pass 550 Turbodown Jacket",
    image: "shirt.png",
    priceUk: 8220,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },
  {
    name: "Columbia Barlow Pass 550 Turbodown Jacket",
    image: "shorts.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },

  {
    name: "Iphone 13",
    image: "phone.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "electronics",
  },
  {
    name: "boxing",
    image: "TV.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "electronics",
  },
  {
    name: "boxing accessories",
    image: "laptop.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "electronics",
  },

  {
    name: "Iphone 13",
    image: "bag.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "accessories",
  },
  {
    name: "boxing",
    image: "glasses.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "accessories",
  },
  {
    name: "boxing accessories",
    image: "hat.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "accessories",
  },

  {
    name: "Iphone 13",
    image: "ball.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "for children",
  },
  {
    name: "boxing",
    image: "doll.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "for children",
  },
  {
    name: "boxing accessories",
    image: "shirt.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "for children",
  },

  {
    name: "Iphone 13",
    image: "steal.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "for sports",
  },
  {
    name: "boxing",
    image: "trainer.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "for sports",
  },
  {
    name: "boxing accessories",
    image: "fat.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "for sports",
  },

  {
    name: "Iphone 13",
    image: "steal.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "cosmetic",
  },
  {
    name: "boxing",
    image: "trainer.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "cosmetic",
  },
  {
    name: "boxing accessories",
    image: "fat.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "cosmetic",
  },
];
