export const Products = [
  {
    name: "222 Columbia Barlow Pass 550 Turbodown Jacket",
    image: "assets/home/HowProfitable/swiper/products/ColumbiaBarlow.png",
    priceUk: 80.62,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },
  {
    name: "Columbia Barlow Pass 550 Turbodown Jacket",
    image: "assets/home/HowProfitable/swiper/products/shirt.png",
    priceUk: 8220,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },
  {
    name: "Columbia Barlow Pass 550 Turbodown Jacket",
    image: "assets/home/HowProfitable/swiper/products/shorts.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 200,
    delivery: 10,
    category: "clothes",
  },
  {
    name: "boxing",
    image: "assets/home/HowProfitable/swiper/products/ColumbiaBarlow.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "electronics",
  },
  {
    name: "boxing accessories",
    image: "assets/home/HowProfitable/swiper/products/ColumbiaBarlow.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "accessories",
  },
  {
    name: "boxing for children",
    image: "assets/home/HowProfitable/swiper/products/ColumbiaBarlow.png",
    priceUk: 80,
    priceUa: 6399,
    economy: 190,
    delivery: 14,
    category: "for children",
  },
];
